name: Immor
on:
  workflow_dispatch:

jobs:
  build:
    name: 启动"${{ matrix.target }}-${{ github.event.inputs.REPO_BRANCH }}"触发编译
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
    
    steps:
    - name: 密匙检测（密匙为空则退出）
      run: |
        cd ${GITHUB_WORKSPACE}
        if [[ -z "${{ secrets.REPO_TOKEN }}" ]]; then
          echo "您没有设置仓库密匙，请按教程设置好密匙再来"
          echo "REPO_TOKEN密匙制作教程：https://git.io/jm.md"
          exit 1
        fi
    
    - name: 准备结束
      uses: actions/checkout@v3
      
    - name: Delete releases and workflows runs
      uses: 281677160/delete-releases-workflows@main
      with:
        delete_releases: true
        delete_tags: true
        releases_keep_latest: 2
        releases_keep_keyword: targz/Update
        delete_workflows: true
        workflows_keep_day: 10
        workflows_keep_keyword: 281
        out_log: true
        gh_token: ${{ secrets.REPO_TOKEN }}
